/**
 * The curated icon set for the glass world. Import from here (not directly from
 * `lucide-react-native`) so every screen draws from one vocabulary and swapping
 * an icon is a one-line change. All are line icons — never emoji.
 */
export {
  // Nav + chrome
  House,
  ChartColumn,
  Settings2,
  UserRound,
  CalendarDays,
  Bell,
  Plus,
  ChevronLeft,
  ChevronRight,
  SquarePen,
  X,
  Check,
  LogOut,
  // Settings sections
  Volume2,
  AudioLines,
  Mic,
  MessageSquareText,
  Vibrate,
  Sun,
  Database,
  Headphones,
  Speaker,
  // Drill / stats
  Play,
  Pause,
  Camera,
  Repeat,
  Timer,
  Target,
  Activity,
  Trophy,
  Trash2,
  // Aether study app
  Send,
  Sparkles,
  BookOpen,
  GraduationCap,
  Brain,
  Rocket,
  FileText,
  Bot,
  Music,
  Eye,
  EyeOff,
  SendHorizontal,
  ArrowRight,
  RefreshCw,
  Clock,
  Flag,
  AlertCircle,
  Loader,
  Map,
  SkipBack,
  SkipForward,
  Lock,
  ChevronDown,
  // Subject icons (premium replacements for the old subject emoji)
  Calculator,
  Code,
  Dna,
  Atom,
  Pill,
  Wrench,
  Languages,
  ScrollText,
  TrendingUp,
} from 'lucide-react-native';
